######################################################################
# Automatically generated by qmake (3.0) Mon May 16 10:02:21 2016
######################################################################

TEMPLATE = lib
CONFIG += staticlib
TARGET = enet
INCLUDEPATH += . \
./include

DEFINES += HAS_SOCKLEN_T

SOURCES += callbacks.c \
           compress.c \
           host.c \
           list.c \
           packet.c \
           peer.c \
           protocol.c \
           unix.c
