######################################################################
# Automatically generated by qmake (3.0) Mon May 16 10:00:13 2016
######################################################################

TEMPLATE = subdirs

SUBDIRS += server enet client

server.depends = enet

client.depends = enet



